#!/bin/bash

DIR=`realpath $(dirname $0)`

function link {
	mkdir -p `dirname $2`
	ln -s $DIR/$1 $2
}

function install {
	MODULES=`whiptail --title "dotfiles" --separate-output --checklist "Which configs do you want to install?" 20 75 5 \
		"bspwm" "Tiling Window Manager" ON \
		"neofetch" "Information Tool" ON \
		"picom" "Compositor" ON \
		"sxhkd" "Hotkey Daemon" ON \
		"zsh" "Unix Shell" ON \
		3>&2 2>&1 1>&3`
	if [ -z "$MODULES" ]; then
		exit
	fi
	if !(whiptail --title "dotfiles" --yesno "The backup script is currently under development.\nInstall the configs at your own risk!\n\nDo you really want to proceed?" 20 75); then
		exit
	fi
	for MODULE in $MODULES; do
		case $MODULE in
			"bspwm") link home/config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc ;;
			"neofetch") link home/config/neofetch/config.conf ~/.config/neofetch/config.conf ;;
			"picom") link home/config/picom/picom.conf ~/.config/picom/picom.conf ;;
			"sxhkd") link home/config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc ;;
			"zsh") link home/zshrc ~/.zshrc ;;
		esac
	done
}

function restore {
	whiptail --title "dotfiles" --msgbox "This feature is currently under development." 20 75
}

MODE=`whiptail --title "dotfiles" --menu "What do you want to do?" 20 75 5 \
	"Install" "Install and backup current configs" \
	"Restore" "Restore the backed up configs" \
	3>&2 2>&1 1>&3`

case $MODE in
	"Install") install ;;
	"Restore") restore ;;
esac
