#!/bin/bash

DIR=`realpath $(dirname $0)`

function link {
	mkdir -p `dirname $2`
	ln -s $DIR/$1 $2
}

function install {
	MODULES=`whiptail --title "dotfiles" --separate-output --checklist "Which configs do you want to install?" 20 75 10 \
		"Alacritty" "Terminal Emulator" ON \
		"bsp-layout" "Manage layouts" ON \
		"bspwm" "Tiling Window Manager" ON \
		"Dunst" "Notification Daemon" ON \
		"Neofetch" "Information Tool" ON \
		"Picom" "Compositor" ON \
		"Polybar" "Status Bar" ON \
		"Rofi" "Application Launcher" ON \
		"sxhkd" "Hotkey Daemon" ON \
		"Wallpapers" "Wallpaper Collection" ON \
		"Zsh" "Unix Shell" ON \
		3>&2 2>&1 1>&3`
	if [ -z "$MODULES" ]; then
		exit
	fi
	if !(whiptail --title "dotfiles" --yesno "The backup script is currently under development.\nInstall the configs at your own risk!\n\nDo you really want to proceed?" 20 75); then
		exit
	fi
	for MODULE in $MODULES; do
		case $MODULE in
			"Alacritty") link home/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml ;;
			"bsp-layout") link home/config/bsp-layout/layoutrc ~/.config/bsp-layout/layoutrc ;;
			"bspwm") link home/config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc ;;
			"Dunst") link home/config/dunst/dunstrc ~/.config/dunst/dunstrc ;;
			"Neofetch") link home/config/neofetch/config.conf ~/.config/neofetch/config.conf ;;
			"Picom") link home/config/picom/picom.conf ~/.config/picom/picom.conf ;;
			"Polybar") link home/config/polybar/config ~/.config/polybar/config ;;
			"Rofi") link home/config/rofi/config.rasi ~/.config/rofi/config.rasi ;;
			"sxhkd") link home/config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc ;;
			"Wallpapers")
				link home/config/wallpapers/onedark.png ~/.config/wallpapers/onedark.png
			;;
			"Zsh") link home/zshrc ~/.zshrc ;;
		esac
	done
}

function restore {
	whiptail --title "dotfiles" --msgbox "This feature is currently under development." 20 75
}

MODE=`whiptail --title "dotfiles" --menu "What do you want to do?" 20 75 10 \
	"Install" "Install and backup current configs" \
	"Restore" "Restore the backed up configs" \
	"Update" "Check for updates" \
	3>&2 2>&1 1>&3`

case $MODE in
	"Install") install ;;
	"Restore") restore ;;
	"Update") git pull ;;
esac
